# .github/workflows/mysql-deploy.yml
on: [push]

jobs:
  build:
    runs-on: linux-latest
    steps:
    - uses: actions/checkout@v1
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/mysql-action@v1
      with:
        server-name: phpmysqlserver1.mysql.database.azure.com
        connection-string: $con=mysqli_init(); mysqli_ssl_set($con, NULL, NULL, {ca-cert filename}, NULL, NULL); mysqli_real_connect($con, "phpmysqlserver1.mysql.database.azure.com", "malak@phpmysqlserver1", {your_password}, {your_database}, 3306);
        sql-file: './sqlFile.sql'
