# .github/workflows/mysql-deploy.yml
on: [push]

jobs:
  build:
    runs-on: linux-latest
    steps:
    - uses: actions/checkout@v1
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/mysql-action@v1
      with:
        server-name: phpmysqlserver1.mysql.database.azure.com
        connection-string: ${{ secrets.AZURE_MYSQL_CONNECTION_STRING }}
        sql-file: './sqlFile.sql'
